# -*- coding: utf-8 -*-
"""AI Agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CktDcCddxzCN58xFyeNGnLFSjVzndtjL
"""

!pip install -qU crewai[tools,agentops]==1.12.1
!pip install agentops
!pip install litellm
!pip install -qU tavily-python scrapegraph-py
!pip install sentence-transformers -q

from crewai import Agent, Task , Crew, Process, LLM
from crewai.tools import tool
import agentops
import os
from pydantic import BaseModel, Field
from typing import List
from tavily import TavilyClient
from scrapegraph_py import Client
import json

os.environ["AGENTOPS_API_KEY"] = os.getenv("AGENTOPS_API_KEY", "Your_Api_key")
os.environ["GROQ_API_KEY"] = os.getenv("GROQ_API_KEY", "Your_Api_key")
os.environ["OPENAI_API_KEY"] = "dummy-not-used"

agentops.init(
    api_key= "Your_Api_key",
    skip_auto_end_session = True,
    default_tags=['crewai']

)

output_dir = "./ai-agent-output"
os.makedirs(output_dir, exist_ok=True)

basic_llm = LLM(
    model="groq/llama-3.3-70b-versatile",
    provider="groq",  # explicitly switch provider
    temperature=0,
    max_tokens=4000,

)
search_client = TavilyClient(api_key="Your_Api_key")
Scrape_client = Client(api_key="Your_Api_key")

search_client.search("coffe machine site : amzon.eg")

no_keywords = 10

"""## setup agent A"""

class SuggestedSearchQuries(BaseModel):
  queries: List[str] = Field(..., description="A list of suggested search queries",
                           min_length=1, max_length=no_keywords)

search_queries_recommendations_agent= Agent(
role="search Quires Recommendation Agent",
goal = """To Provide a list of suggested search queries to be passed to the search engine.
The queries msut be varied and looking for specific items.""",
backstory = "the agent is designed to lookig for products by providing a list of suggested queries to be passed to the search engine.",
llm = basic_llm,
verbose= True,
)

search_queries_recommendations_task = Task(
    description="""our company wants to buy {product_name} machine at the best price (value for price),
    The agent is designed to lookig for products by providing a list of suggested queries to be passed to the search engine,
    The company wants to buy from these websites {websites_list},
    the company wants to reach all available products to be compared with each other,
    the stroes must sell the products in {countrey_name},
    generate at max queries {no_keywords},
    the search keyword must be in {language},
    could mension specific brands,
    the search query must reach an ecommerce webpage for products not a blog or listing page
    """,

expected_output = "A json object containing a list of suggested search queries",
output_json = SuggestedSearchQuries,
output_file= os.path.join(output_dir,"step1_suggested_search_queries.json"),
agent = search_queries_recommendations_agent,
)

"""##Second Agent"""

class SingleSearchResult(BaseModel):
  title: str
  url: str
  score: float
  content: str
class AllSearchResults(BaseModel):
  results: List[SingleSearchResult] = Field(..., description="the page url")
@tool
def search_engine_tool(queries:str):
  """ useful for search based queries, used to find current information about any query related """
  return search_client.search(queries)

search_engine_agent = Agent(
    role = "search engine agent",
    goal = "search based queries, used to find current information about any query related",
    backstory = "the agent is designed to search based queries, used to find current information about any query related",
    llm = basic_llm,
    verbose = True,
    tools = [search_engine_tool]

)
search_engine_task = Task(
    description="""the task is to search for products based on the suggested search queries,
    you have to collect results from search queries,
    ignore any suspicious or irrelevant results with score less than (0.10),
    the search results will be used to compare prices of products from diffrent websites""",
    expected_output = "A json object containing the search results",
    output_json = AllSearchResults,
    output_file= os.path.join(output_dir,"step2_search_results.json"),
    agent = search_engine_agent,
)

# {
#     "results":[
#         {
#             "title":"",
#             "url":"",
#             "score":"",
#             "content":"",
#             "search_query":""
#         }
#     ]

#     }

"""### Third Agent"""

class ProductSpec(BaseModel):
    specification_name: str
    specification_value: str

class SingleExtractedProduct(BaseModel):
    page_url: str = Field(..., title="The original url of the product page")
    product_title: str = Field(..., title="The title of the product")
    product_image_url: str = Field(..., title="The url of the product image")
    product_url: str = Field(..., title="The url of the product")
    product_current_price: float = Field(..., title="The current price of the product")
    product_original_price: float = Field(title="The original price of the product before discount. Set to None if no discount", default=None)
    product_discount_percentage: float = Field(title="The discount percentage of the product. Set to None if no discount", default=None)

    product_specs: List[ProductSpec] = Field(..., title="The specifications of the product. Focus on the most important specs to compare.", min_items=1, max_items=5)

    agent_recommendation_rank: int = Field(..., title="The rank of the product to be considered in the final procurement report. (out of 5, Higher is Better) in the recommendation list ordering from the best to the worst")
    agent_recommendation_notes: List[str]  = Field(..., title="A set of notes why would you recommend or not recommend this product to the company, compared to other products.")


class AllExtractedProducts(BaseModel):
  Products : List[SingleExtractedProduct]

@tool
def scrape_website_tool(page_url:str,required_fileds: list):
  """used for extracting the data form the webpage or the url"""
  scrape_client = Scrape_client
  details = scrape_client.smartscraper(
      website_url=page_url,
      user_prompt = "Extract" + json.dumps(required_fileds,ensure_ascii= False)+ "from the web page",
  )
  return {
      "page_url": page_url,
      "score": details.score,
      "content": details.content,
  }

Scraping_Web_Agent= Agent(
    role= "Scraping Web Agent",
    goal= "extract the data form the webpage or the url",
    backstory = "after we got the search queries and the url that specified to it now the agent is designed to extract the data form every webpage or the url, this data used to decide which best product to buy",
    llm= basic_llm,
    verbose= True,
    tools = [scrape_website_tool],
)

ScrapingWebTask= Task(
    description = "the task is to extract the important products from the webpage or the url",
    expected_output= "A json object containing the scraped products details",
    output_json = AllExtractedProducts,
    output_file= os.path.join(output_dir,"step3_scraped_data.json"),
    agent = Scraping_Web_Agent,
)

AllExtractedProducts.schema_json()

"""### Final Agent"""

procrutment_report_agent = Agent(
    role = "procrutment report author ",
    goal= " to generate a procrutment report based on the scraped data",
    backstory= "the agent is designed to generate a procrutment report based on the scraped",
    llm = basic_llm,
    verbose = True,
)

procurement_report_author_task = Task(
    description="\n".join([
        "The task is to generate a professional HTML page for the procurement report.",
        "You have to use Bootstrap CSS framework for a better UI.",
        "Use the provided context about the company to make a specialized report.",
        "The report will include the search results and prices of products from different websites.",
        "The report should be structured with the following sections:",
        "1. Executive Summary: A brief overview of the procurement process and key findings.",
        "2. Introduction: An introduction to the purpose and scope of the report.",
        "3. Methodology: A description of the methods used to gather and compare prices.",
        "4. Findings: Detailed comparison of prices from different websites, including tables and charts.",
        "5. Analysis: An analysis of the findings, highlighting any significant trends or observations.",
        "6. Recommendations: Suggestions for procurement based on the analysis.",
        "7. Conclusion: A summary of the report and final thoughts.",
        "8. Appendices: Any additional information, such as raw data or supplementary materials.",
    ]),
    expected_output = "A professional html page for the procrutment report",
    output_file= os.path.join(output_dir,"step4_procrutment_report.html"),
    agent = procrutment_report_agent,
)

"""##Run the AI crew"""

Yousef_crew = Crew(
    agents= [search_queries_recommendations_agent,search_engine_agent,Scraping_Web_Agent,procrutment_report_agent],
    tasks= [search_queries_recommendations_task,search_engine_task,ScrapingWebTask,procurement_report_author_task],
    process = Process.sequential,
    embedder={
        "provider": "huggingface",
        "config": {
            "model": "sentence-transformers/all-MiniLM-L6-v2"
        }
    }
)

crew_results= Yousef_crew.kickoff(
    inputs={"product_name":"coffe machine for the office",
            "websites_list":["www.amazon.eg","www.noon.com"],
            "no_keywords":10,
            "countrey_name":"Egypt",
            "language":"english",
})
